- hosts: localhost
  vars:
    source_key: "./.ssh/id_rsa"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
    exercism_token: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          66356130643163306437633766353833303536626437633662666564303433376135633438633032
          3032666130643862663963633733656438373536383663300a373030323333653163613563363163
          61303632333838626135333035393637343438396638633565326439373162326461633030326665
          6237353834303365330a623830383964363163313363323732393232353536616632623931373432
          38626566663936343531666433613935653339643339373931626530666530316534373739663838
          6366323039313231393264363237346565636234306137633735
  become: true
  pre_tasks:
    - name: Update cache
      apt: 
        update_cache: true
      tags:
        - install
  tasks: 

  - name: core
    include_tasks: tasks/core.yml
    tags:
      - install
      - core

  - name: ssh
    include_tasks: tasks/ssh.yml
    tags:
      - install
      - ssh

  - name: python
    include_tasks: tasks/python.yml
    tags:
      - install
      - python

  - name: git
    include_tasks: tasks/git.yml
    tags:
      - install
      - git

  - name: zsh
    include_tasks: tasks/zsh.yml
    tags:
      - install
      - zsh
    
  - name: .dotfiles
    include_tasks: tasks/dotfiles.yml
    tags:
      - install
      - dotfiles

  - name: node
    include_tasks: tasks/node.yml
    tags:
      - install
      - node

  - name: nvim
    include_tasks: tasks/nvim.yml
    tags:
      - install
      - nvim

  - name: rust
    include_tasks: tasks/rust.yml
    tags:
      - install
      - rust

  - name: exercism.io
    include_tasks: tasks/exercism.yml
    tags:
      - install
      - exercism

  - name: emanote
    include_tasks: tasks/emanote.yml
    tags:
      - install
      - emanote

  - name: tools
    include_tasks: tasks/tools.yml
    tags:
      - install
      - tools
      - docker
      - git
