- name: Install nix
  tags: [ install, emanote ]
  become: yes
  become_user: "{{ lookup('env', 'USER') }}"
  shell: "curl -L https://nixos.org/nix/install | sh && chmod +x {{ lookup('env', 'HOME') }}/.nix-profile/etc/profile.d/nix.sh"

- name: Configure nix & Install Emanote
  tags: [ install, emanote ]
  become: yes
  become_user: "{{ lookup('env', 'USER') }}"
  shell: ". {{ lookup('env', 'HOME') }}/.nix-profile/etc/profile.d/nix.sh && nix-env -if https://github.com/srid/emanote/archive/refs/heads/master.tar.gz"

- name: Move emanote to usr/local/bin
  tags: [ install, emanote ]
  copy:
    src: "{{ lookup('env', 'HOME') }}/.nix-profile/bin/emanote"
    dest: "/usr/local/bin/emanote"
    owner: "{{ lookup('env', 'USER') }}"
    mode: +x

- name: Clone Knowledge Base
  tags: [ install, emanote ]
  become: yes
  become_user: "{{ lookup('env', 'USER') }}"
  ansible.builtin.git:
    repo: 'git@github.com:KCaverly/kb.git'
    dest: "{{ lookup('env', 'HOME') }}/personal/kb"
    recursive: yes
    update: yes
    version: master
    accept_hostkey: true
    key_file: "{{ dest_key }}"
