- name: Install Neovim
  tags: [ install, neovim ]
  shell: "add-apt-repository ppa:neovim-ppa/unstable && sudo apt-get update && sudo apt-get install -y neovim"

- name: Install Packer
  tags: [ install, neovim ]
  become: yes
  become_user: "{{ lookup('env', 'USER') }}"
  ansible.builtin.git:
    repo: 'git@github.com:wbthomason/packer.nvim.git'
    dest: "{{ lookup('env', 'HOME') }}/.local/share/nvim/site/pack/packer/start/packer.nvim"
    update: yes
    accept_hostkey: yes
    version: master

- name: neovim | Install emanote.nvim
  tags: [ install, neovim ]
  become: yes
  become_user: "{{ lookup('env', 'USER') }}"
  ansible.builtin.git:
    repo: 'git@github.com:KCaverly/emanote.nvim.git'
    dest: "{{ lookup('env', 'HOME') }}/personal/emanote.nvim"
    update: yes
    accept_hostkey: yes
    version: master
