- name: Python | Install python
  tags: [ install, python ]
  shell: apt install python3 && apt autoremove

- name: Python | Install poetry
  tags: [ install, python, poetry ]
  shell: curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -

- name: Python | Install pyright
  tags: [ install, python, lsp ]
  shell: npm install --global pyright

- name: Python | Install pre-commit
  tags: [ install, python, poetry ]
  shell: pip install pre-commit

- name: Python | Install nltk_data
  tags: [ install, python ]
  shell: python -c "import nltk; nltk.download('all', download_dir='/usr/local/share/nltk_data/')"
