- name: python | Install pyenv
  tags: [ install, python ]
  ansible.builtin.git:
    repo: 'https://github.com/pyenv/pyenv.git'
    dest: "{{ lookup('env', 'HOME') }}/.pyenv"
    recursive: true
    update: yes
    version: master

- name: python | Install poetry
  tags: [ install, python ]
  shell: curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -

- name: python | Install pre-commit
  tags: [ install, python ]
  shell: pip install pre-commit
